name: Waka Readme

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 11:30 PM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: false               # ❌ hides "From: ... To: ..." title
          SHOW_TOTAL: true               # ✅ optional: shows total time
          SHOW_TIME: true                # ✅ shows time per language
          SHOW_MASKED_TIME: false        # ✅ shows exact hours
          SHOW_LANGUAGES: true           # ✅ shows language bars
